name: microservice-balance

volumes:
  postgres-data:
    driver: local
  pgadmin4-data:
    driver: local
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  balance-service-http-data:
    driver: local

services:

  balance-service-http:
    build:
      context: ./deployment/docker/balance/http
      dockerfile: Dockerfile
    volumes:
      - ./:/balance
      - ./config/balance:/config/balance
      - ./.go-pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /balance
    ports:
      - 5050:8080
    # env_file:
    #   - .env
    environment:
      GOCACHE: /go-cache
      GOPATH: /go/pkg
    # depends_on:
    #   - postgres

  postgres:
    # profiles: [donotstart]
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=balance
      - POSTGRES_PASSWORD=balance
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  pgadmin4:
    # profiles: [donotstart]
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adminz@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8080
    restart: unless-stopped
    ports:
      - 8082:8080

  prometheus:
    # profiles: [donotstart]
    container_name: prometheus_container
    image: prom/prometheus
    restart: unless-stopped
    volumes: 
      - ./deployment/prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  grafana:
    # profiles: [donotstart]
    container_name: grafana_container
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./deployment/grafana:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - 3000:3000