name: microservice-balance
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=demo_password
  
  pgadmin4:
    # profiles: [donotstart]
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adminz@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8080
    restart: always
    ports:
      - 8082:8080
