postgres:
  addr: postgres:5432 # POSTGRES_ADDR
  user: balance # POSTGRES_USER
  password: balance # POSTGRES_PASSWORD
  database: balance # POSTGRES_DB
  schema: public # POSTGRES_SCHEMA
  max_idle_connections: 10 # POSTGRES_MAX_IDLE_CONNECTIONS
  max_open_connections: 100 # POSTGRES_MAX_OPEN_CONNECTIONS
  connection_max_lifetime: 1h # POSTGRES_CONNECTION_MAX_LIFETIME
  return_utc: true # POSTGRES_RETURN_UTC
  migrations_dir: ./internal/balance/migrations/postgres # POSTGRES_MIGRATIONS_DIR

use_cases:
  report_revenue_export:
    folder: /tmp/report_revenue_export
    ttl: 1h
    url: /data/report_revenue_export/
    zip: true
    
jwt:
  secret: "secret_key"
  ttl: 24h

http:
  addr: 0.0.0.0:8080
  api_prefix: /api
  handler_timeout: 10s
  read_timeout: 10s
  write_timeout: 10s
  swagger:
    enabled: true
    path: /swagger
  cors:
    allowed_origins:
      - "*"
  tls:
    enabled: false
    cert_file: ./certs/cert.pem
    key_file: ./certs/key.pem
  

prometheus:
  port: 8081
  path: /metrics

grpc:
  addr: 0.0.0.0:8083
  keepalive:
    time: 10s
    timeout: 10s
    max_connection_idle: 10s
    max_connection_age: 10s
    max_connection_age_grace: 10s

jaeger:
  host: localhost:6831
  service_name: balance-service
  log_spans: true

mode: dev

lagging:
  # enabled: true
  enabled: false
