name: microservice-balance

volumes:
  postgres-data:
    driver: local
  pgadmin4-data:
    driver: local
  grafana-data:
    driver: local

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=demo_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin4:
    # profiles: [donotstart]
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adminz@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8080
    restart: unless-stopped
    ports:
      - 8082:8080

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes: 
      - ./prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-data: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - 3000:3000