// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: balance.proto

package balance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     int64                  `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Reserved      int64                  `protobuf:"varint,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetBalanceResponse) GetReserved() int64 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{2}
}

func (x *DepositRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductTitle  string                 `protobuf:"bytes,3,opt,name=product_title,json=productTitle,proto3" json:"product_title,omitempty"`
	OrderId       int64                  `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveRequest) GetProductTitle() string {
	if x != nil {
		return x.ProductTitle
	}
	return ""
}

func (x *ReserveRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReserveCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCancelRequest) Reset() {
	*x = ReserveCancelRequest{}
	mi := &file_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCancelRequest) ProtoMessage() {}

func (x *ReserveCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCancelRequest.ProtoReflect.Descriptor instead.
func (*ReserveCancelRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveCancelRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveCancelRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveCancelRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveCancelRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReserveConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveConfirmRequest) Reset() {
	*x = ReserveConfirmRequest{}
	mi := &file_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveConfirmRequest) ProtoMessage() {}

func (x *ReserveConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveConfirmRequest.ProtoReflect.Descriptor instead.
func (*ReserveConfirmRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveConfirmRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveConfirmRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveConfirmRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveConfirmRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{6}
}

func (x *TransferRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *TransferRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReportTransactionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor           string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit            uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sorting          string                 `protobuf:"bytes,4,opt,name=sorting,proto3" json:"sorting,omitempty"`
	SortingDirection string                 `protobuf:"bytes,5,opt,name=sorting_direction,json=sortingDirection,proto3" json:"sorting_direction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportTransactionsRequest) Reset() {
	*x = ReportTransactionsRequest{}
	mi := &file_balance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransactionsRequest) ProtoMessage() {}

func (x *ReportTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ReportTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{7}
}

func (x *ReportTransactionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportTransactionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ReportTransactionsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReportTransactionsRequest) GetSorting() string {
	if x != nil {
		return x.Sorting
	}
	return ""
}

func (x *ReportTransactionsRequest) GetSortingDirection() string {
	if x != nil {
		return x.SortingDirection
	}
	return ""
}

type ReportTransactionsResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Transactions  []*ReportTransactionsTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Cursor        string                           `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore       bool                             `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransactionsResponse) Reset() {
	*x = ReportTransactionsResponse{}
	mi := &file_balance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransactionsResponse) ProtoMessage() {}

func (x *ReportTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ReportTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTransactionsResponse) GetTransactions() []*ReportTransactionsTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ReportTransactionsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ReportTransactionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ReportTransactionsTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Transaction:
	//
	//	*ReportTransactionsTransaction_Deposit
	//	*ReportTransactionsTransaction_Spend
	//	*ReportTransactionsTransaction_Transfer
	Transaction   isReportTransactionsTransaction_Transaction `protobuf_oneof:"transaction"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransactionsTransaction) Reset() {
	*x = ReportTransactionsTransaction{}
	mi := &file_balance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransactionsTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransactionsTransaction) ProtoMessage() {}

func (x *ReportTransactionsTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransactionsTransaction.ProtoReflect.Descriptor instead.
func (*ReportTransactionsTransaction) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{9}
}

func (x *ReportTransactionsTransaction) GetTransaction() isReportTransactionsTransaction_Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ReportTransactionsTransaction) GetDeposit() *ReportTransactionsTransactionDeposit {
	if x != nil {
		if x, ok := x.Transaction.(*ReportTransactionsTransaction_Deposit); ok {
			return x.Deposit
		}
	}
	return nil
}

func (x *ReportTransactionsTransaction) GetSpend() *ReportTransactionsTransactionSpend {
	if x != nil {
		if x, ok := x.Transaction.(*ReportTransactionsTransaction_Spend); ok {
			return x.Spend
		}
	}
	return nil
}

func (x *ReportTransactionsTransaction) GetTransfer() *ReportTransactionsTransactionTransfer {
	if x != nil {
		if x, ok := x.Transaction.(*ReportTransactionsTransaction_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

type isReportTransactionsTransaction_Transaction interface {
	isReportTransactionsTransaction_Transaction()
}

type ReportTransactionsTransaction_Deposit struct {
	Deposit *ReportTransactionsTransactionDeposit `protobuf:"bytes,1,opt,name=deposit,proto3,oneof"`
}

type ReportTransactionsTransaction_Spend struct {
	Spend *ReportTransactionsTransactionSpend `protobuf:"bytes,2,opt,name=spend,proto3,oneof"`
}

type ReportTransactionsTransaction_Transfer struct {
	Transfer *ReportTransactionsTransactionTransfer `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

func (*ReportTransactionsTransaction_Deposit) isReportTransactionsTransaction_Transaction() {}

func (*ReportTransactionsTransaction_Spend) isReportTransactionsTransaction_Transaction() {}

func (*ReportTransactionsTransaction_Transfer) isReportTransactionsTransaction_Transaction() {}

type ReportTransactionsTransactionDeposit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransactionsTransactionDeposit) Reset() {
	*x = ReportTransactionsTransactionDeposit{}
	mi := &file_balance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransactionsTransactionDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransactionsTransactionDeposit) ProtoMessage() {}

func (x *ReportTransactionsTransactionDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransactionsTransactionDeposit.ProtoReflect.Descriptor instead.
func (*ReportTransactionsTransactionDeposit) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{10}
}

func (x *ReportTransactionsTransactionDeposit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportTransactionsTransactionDeposit) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReportTransactionsTransactionDeposit) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ReportTransactionsTransactionDeposit) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTransactionsTransactionDeposit) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReportTransactionsTransactionDeposit) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReportTransactionsTransactionSpend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductTitle  string                 `protobuf:"bytes,5,opt,name=product_title,json=productTitle,proto3" json:"product_title,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransactionsTransactionSpend) Reset() {
	*x = ReportTransactionsTransactionSpend{}
	mi := &file_balance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransactionsTransactionSpend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransactionsTransactionSpend) ProtoMessage() {}

func (x *ReportTransactionsTransactionSpend) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransactionsTransactionSpend.ProtoReflect.Descriptor instead.
func (*ReportTransactionsTransactionSpend) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{11}
}

func (x *ReportTransactionsTransactionSpend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportTransactionsTransactionSpend) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ReportTransactionsTransactionSpend) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReportTransactionsTransactionSpend) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReportTransactionsTransactionSpend) GetProductTitle() string {
	if x != nil {
		return x.ProductTitle
	}
	return ""
}

func (x *ReportTransactionsTransactionSpend) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReportTransactionsTransactionSpend) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTransactionsTransactionSpend) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReportTransactionsTransactionSpend) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReportTransactionsTransactionTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          int64                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTransactionsTransactionTransfer) Reset() {
	*x = ReportTransactionsTransactionTransfer{}
	mi := &file_balance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTransactionsTransactionTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTransactionsTransactionTransfer) ProtoMessage() {}

func (x *ReportTransactionsTransactionTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTransactionsTransactionTransfer.ProtoReflect.Descriptor instead.
func (*ReportTransactionsTransactionTransfer) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{12}
}

func (x *ReportTransactionsTransactionTransfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportTransactionsTransactionTransfer) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ReportTransactionsTransactionTransfer) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ReportTransactionsTransactionTransfer) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReportTransactionsTransactionTransfer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTransactionsTransactionTransfer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReportTransactionsTransactionTransfer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReportRevenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRevenueRequest) Reset() {
	*x = ReportRevenueRequest{}
	mi := &file_balance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRevenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRevenueRequest) ProtoMessage() {}

func (x *ReportRevenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRevenueRequest.ProtoReflect.Descriptor instead.
func (*ReportRevenueRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{13}
}

func (x *ReportRevenueRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ReportRevenueRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type ReportRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ReportRevenueRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRevenueResponse) Reset() {
	*x = ReportRevenueResponse{}
	mi := &file_balance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRevenueResponse) ProtoMessage() {}

func (x *ReportRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRevenueResponse.ProtoReflect.Descriptor instead.
func (*ReportRevenueResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{14}
}

func (x *ReportRevenueResponse) GetRecords() []*ReportRevenueRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type ReportRevenueRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductTitle  string                 `protobuf:"bytes,2,opt,name=product_title,json=productTitle,proto3" json:"product_title,omitempty"`
	TotalRevenue  int64                  `protobuf:"varint,3,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRevenueRecord) Reset() {
	*x = ReportRevenueRecord{}
	mi := &file_balance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRevenueRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRevenueRecord) ProtoMessage() {}

func (x *ReportRevenueRecord) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRevenueRecord.ProtoReflect.Descriptor instead.
func (*ReportRevenueRecord) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{15}
}

func (x *ReportRevenueRecord) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReportRevenueRecord) GetProductTitle() string {
	if x != nil {
		return x.ProductTitle
	}
	return ""
}

func (x *ReportRevenueRecord) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

type AuthSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignInRequest) Reset() {
	*x = AuthSignInRequest{}
	mi := &file_balance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignInRequest) ProtoMessage() {}

func (x *AuthSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignInRequest.ProtoReflect.Descriptor instead.
func (*AuthSignInRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{16}
}

func (x *AuthSignInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthSignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthSignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignInResponse) Reset() {
	*x = AuthSignInResponse{}
	mi := &file_balance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignInResponse) ProtoMessage() {}

func (x *AuthSignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignInResponse.ProtoReflect.Descriptor instead.
func (*AuthSignInResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{17}
}

func (x *AuthSignInResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_balance_proto protoreflect.FileDescriptor

const file_balance_proto_rawDesc = "" +
	"\n" +
	"\rbalance.proto\x12\abalance\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\x12GetBalanceResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\x03R\tavailable\x12\x1a\n" +
	"\breserved\x18\x02 \x01(\x03R\breserved\"Y\n" +
	"\x0eDepositRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\xa0\x01\n" +
	"\x0eReserveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12#\n" +
	"\rproduct_title\x18\x03 \x01(\tR\fproductTitle\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"\x81\x01\n" +
	"\x14ReserveCancelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"\x82\x01\n" +
	"\x15ReserveConfirmRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"M\n" +
	"\x0fTransferRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xa9\x01\n" +
	"\x19ReportTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12\x18\n" +
	"\asorting\x18\x04 \x01(\tR\asorting\x12+\n" +
	"\x11sorting_direction\x18\x05 \x01(\tR\x10sortingDirection\"\x9b\x01\n" +
	"\x1aReportTransactionsResponse\x12J\n" +
	"\ftransactions\x18\x01 \x03(\v2&.balance.ReportTransactionsTransactionR\ftransactions\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x8c\x02\n" +
	"\x1dReportTransactionsTransaction\x12I\n" +
	"\adeposit\x18\x01 \x01(\v2-.balance.ReportTransactionsTransactionDepositH\x00R\adeposit\x12C\n" +
	"\x05spend\x18\x02 \x01(\v2+.balance.ReportTransactionsTransactionSpendH\x00R\x05spend\x12L\n" +
	"\btransfer\x18\x03 \x01(\v2..balance.ReportTransactionsTransactionTransferH\x00R\btransferB\r\n" +
	"\vtransaction\"\xbc\x01\n" +
	"$ReportTransactionsTransactionDeposit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xa0\x02\n" +
	"\"ReportTransactionsTransactionSpend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12#\n" +
	"\rproduct_title\x18\x05 \x01(\tR\fproductTitle\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xc9\x01\n" +
	"%ReportTransactionsTransactionTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x03R\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"@\n" +
	"\x14ReportRevenueRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"O\n" +
	"\x15ReportRevenueResponse\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.balance.ReportRevenueRecordR\arecords\"~\n" +
	"\x13ReportRevenueRecord\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12#\n" +
	"\rproduct_title\x18\x02 \x01(\tR\fproductTitle\x12#\n" +
	"\rtotal_revenue\x18\x03 \x01(\x03R\ftotalRevenue\"K\n" +
	"\x11AuthSignInRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x12AuthSignInResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xa7\x05\n" +
	"\x0eBalanceService\x12G\n" +
	"\n" +
	"GetBalance\x12\x1a.balance.GetBalanceRequest\x1a\x1b.balance.GetBalanceResponse\"\x00\x12<\n" +
	"\aDeposit\x12\x17.balance.DepositRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\aReserve\x12\x17.balance.ReserveRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\rReserveCancel\x12\x1d.balance.ReserveCancelRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x0eReserveConfirm\x12\x1e.balance.ReserveConfirmRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\bTransfer\x12\x18.balance.TransferRequest\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\n" +
	"AuthSignIn\x12\x1a.balance.AuthSignInRequest\x1a\x1b.balance.AuthSignInResponse\"\x00\x12_\n" +
	"\x12ReportTransactions\x12\".balance.ReportTransactionsRequest\x1a#.balance.ReportTransactionsResponse\"\x00\x12P\n" +
	"\rReportRevenue\x12\x1d.balance.ReportRevenueRequest\x1a\x1e.balance.ReportRevenueResponse\"\x00B<Z:github.com/nktknshn/avito-internship-2022/internal/balanceb\x06proto3"

var (
	file_balance_proto_rawDescOnce sync.Once
	file_balance_proto_rawDescData []byte
)

func file_balance_proto_rawDescGZIP() []byte {
	file_balance_proto_rawDescOnce.Do(func() {
		file_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)))
	})
	return file_balance_proto_rawDescData
}

var file_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_balance_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),                     // 0: balance.GetBalanceRequest
	(*GetBalanceResponse)(nil),                    // 1: balance.GetBalanceResponse
	(*DepositRequest)(nil),                        // 2: balance.DepositRequest
	(*ReserveRequest)(nil),                        // 3: balance.ReserveRequest
	(*ReserveCancelRequest)(nil),                  // 4: balance.ReserveCancelRequest
	(*ReserveConfirmRequest)(nil),                 // 5: balance.ReserveConfirmRequest
	(*TransferRequest)(nil),                       // 6: balance.TransferRequest
	(*ReportTransactionsRequest)(nil),             // 7: balance.ReportTransactionsRequest
	(*ReportTransactionsResponse)(nil),            // 8: balance.ReportTransactionsResponse
	(*ReportTransactionsTransaction)(nil),         // 9: balance.ReportTransactionsTransaction
	(*ReportTransactionsTransactionDeposit)(nil),  // 10: balance.ReportTransactionsTransactionDeposit
	(*ReportTransactionsTransactionSpend)(nil),    // 11: balance.ReportTransactionsTransactionSpend
	(*ReportTransactionsTransactionTransfer)(nil), // 12: balance.ReportTransactionsTransactionTransfer
	(*ReportRevenueRequest)(nil),                  // 13: balance.ReportRevenueRequest
	(*ReportRevenueResponse)(nil),                 // 14: balance.ReportRevenueResponse
	(*ReportRevenueRecord)(nil),                   // 15: balance.ReportRevenueRecord
	(*AuthSignInRequest)(nil),                     // 16: balance.AuthSignInRequest
	(*AuthSignInResponse)(nil),                    // 17: balance.AuthSignInResponse
	(*emptypb.Empty)(nil),                         // 18: google.protobuf.Empty
}
var file_balance_proto_depIdxs = []int32{
	9,  // 0: balance.ReportTransactionsResponse.transactions:type_name -> balance.ReportTransactionsTransaction
	10, // 1: balance.ReportTransactionsTransaction.deposit:type_name -> balance.ReportTransactionsTransactionDeposit
	11, // 2: balance.ReportTransactionsTransaction.spend:type_name -> balance.ReportTransactionsTransactionSpend
	12, // 3: balance.ReportTransactionsTransaction.transfer:type_name -> balance.ReportTransactionsTransactionTransfer
	15, // 4: balance.ReportRevenueResponse.records:type_name -> balance.ReportRevenueRecord
	0,  // 5: balance.BalanceService.GetBalance:input_type -> balance.GetBalanceRequest
	2,  // 6: balance.BalanceService.Deposit:input_type -> balance.DepositRequest
	3,  // 7: balance.BalanceService.Reserve:input_type -> balance.ReserveRequest
	4,  // 8: balance.BalanceService.ReserveCancel:input_type -> balance.ReserveCancelRequest
	5,  // 9: balance.BalanceService.ReserveConfirm:input_type -> balance.ReserveConfirmRequest
	6,  // 10: balance.BalanceService.Transfer:input_type -> balance.TransferRequest
	16, // 11: balance.BalanceService.AuthSignIn:input_type -> balance.AuthSignInRequest
	7,  // 12: balance.BalanceService.ReportTransactions:input_type -> balance.ReportTransactionsRequest
	13, // 13: balance.BalanceService.ReportRevenue:input_type -> balance.ReportRevenueRequest
	1,  // 14: balance.BalanceService.GetBalance:output_type -> balance.GetBalanceResponse
	18, // 15: balance.BalanceService.Deposit:output_type -> google.protobuf.Empty
	18, // 16: balance.BalanceService.Reserve:output_type -> google.protobuf.Empty
	18, // 17: balance.BalanceService.ReserveCancel:output_type -> google.protobuf.Empty
	18, // 18: balance.BalanceService.ReserveConfirm:output_type -> google.protobuf.Empty
	18, // 19: balance.BalanceService.Transfer:output_type -> google.protobuf.Empty
	17, // 20: balance.BalanceService.AuthSignIn:output_type -> balance.AuthSignInResponse
	8,  // 21: balance.BalanceService.ReportTransactions:output_type -> balance.ReportTransactionsResponse
	14, // 22: balance.BalanceService.ReportRevenue:output_type -> balance.ReportRevenueResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_balance_proto_init() }
func file_balance_proto_init() {
	if File_balance_proto != nil {
		return
	}
	file_balance_proto_msgTypes[9].OneofWrappers = []any{
		(*ReportTransactionsTransaction_Deposit)(nil),
		(*ReportTransactionsTransaction_Spend)(nil),
		(*ReportTransactionsTransaction_Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_proto_goTypes,
		DependencyIndexes: file_balance_proto_depIdxs,
		MessageInfos:      file_balance_proto_msgTypes,
	}.Build()
	File_balance_proto = out.File
	file_balance_proto_goTypes = nil
	file_balance_proto_depIdxs = nil
}
