// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: balance.proto

package balance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     int64                  `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Reserved      int64                  `protobuf:"varint,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetBalanceResponse) GetReserved() int64 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{2}
}

func (x *DepositRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DepositRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductTitle  string                 `protobuf:"bytes,3,opt,name=product_title,json=productTitle,proto3" json:"product_title,omitempty"`
	OrderId       int64                  `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveRequest) GetProductTitle() string {
	if x != nil {
		return x.ProductTitle
	}
	return ""
}

func (x *ReserveRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReserveCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCancelRequest) Reset() {
	*x = ReserveCancelRequest{}
	mi := &file_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCancelRequest) ProtoMessage() {}

func (x *ReserveCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCancelRequest.ProtoReflect.Descriptor instead.
func (*ReserveCancelRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveCancelRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveCancelRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveCancelRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveCancelRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReserveConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveConfirmRequest) Reset() {
	*x = ReserveConfirmRequest{}
	mi := &file_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveConfirmRequest) ProtoMessage() {}

func (x *ReserveConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveConfirmRequest.ProtoReflect.Descriptor instead.
func (*ReserveConfirmRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveConfirmRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveConfirmRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveConfirmRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReserveConfirmRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{6}
}

func (x *TransferRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *TransferRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *TransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AuthSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignInRequest) Reset() {
	*x = AuthSignInRequest{}
	mi := &file_balance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignInRequest) ProtoMessage() {}

func (x *AuthSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignInRequest.ProtoReflect.Descriptor instead.
func (*AuthSignInRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{7}
}

func (x *AuthSignInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthSignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthSignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignInResponse) Reset() {
	*x = AuthSignInResponse{}
	mi := &file_balance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignInResponse) ProtoMessage() {}

func (x *AuthSignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignInResponse.ProtoReflect.Descriptor instead.
func (*AuthSignInResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{8}
}

func (x *AuthSignInResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_balance_proto protoreflect.FileDescriptor

const file_balance_proto_rawDesc = "" +
	"\n" +
	"\rbalance.proto\x12\abalance\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\x12GetBalanceResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\x03R\tavailable\x12\x1a\n" +
	"\breserved\x18\x02 \x01(\x03R\breserved\"Y\n" +
	"\x0eDepositRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\xa0\x01\n" +
	"\x0eReserveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12#\n" +
	"\rproduct_title\x18\x03 \x01(\tR\fproductTitle\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"\x81\x01\n" +
	"\x14ReserveCancelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"\x82\x01\n" +
	"\x15ReserveConfirmRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"M\n" +
	"\x0fTransferRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"K\n" +
	"\x11AuthSignInRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x12AuthSignInResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xf4\x03\n" +
	"\x0eBalanceService\x12G\n" +
	"\n" +
	"GetBalance\x12\x1a.balance.GetBalanceRequest\x1a\x1b.balance.GetBalanceResponse\"\x00\x12<\n" +
	"\aDeposit\x12\x17.balance.DepositRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\aReserve\x12\x17.balance.ReserveRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\rReserveCancel\x12\x1d.balance.ReserveCancelRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x0eReserveConfirm\x12\x1e.balance.ReserveConfirmRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\bTransfer\x12\x18.balance.TransferRequest\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\n" +
	"AuthSignIn\x12\x1a.balance.AuthSignInRequest\x1a\x1b.balance.AuthSignInResponse\"\x00B<Z:github.com/nktknshn/avito-internship-2022/internal/balanceb\x06proto3"

var (
	file_balance_proto_rawDescOnce sync.Once
	file_balance_proto_rawDescData []byte
)

func file_balance_proto_rawDescGZIP() []byte {
	file_balance_proto_rawDescOnce.Do(func() {
		file_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)))
	})
	return file_balance_proto_rawDescData
}

var file_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_balance_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),     // 0: balance.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 1: balance.GetBalanceResponse
	(*DepositRequest)(nil),        // 2: balance.DepositRequest
	(*ReserveRequest)(nil),        // 3: balance.ReserveRequest
	(*ReserveCancelRequest)(nil),  // 4: balance.ReserveCancelRequest
	(*ReserveConfirmRequest)(nil), // 5: balance.ReserveConfirmRequest
	(*TransferRequest)(nil),       // 6: balance.TransferRequest
	(*AuthSignInRequest)(nil),     // 7: balance.AuthSignInRequest
	(*AuthSignInResponse)(nil),    // 8: balance.AuthSignInResponse
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_balance_proto_depIdxs = []int32{
	0, // 0: balance.BalanceService.GetBalance:input_type -> balance.GetBalanceRequest
	2, // 1: balance.BalanceService.Deposit:input_type -> balance.DepositRequest
	3, // 2: balance.BalanceService.Reserve:input_type -> balance.ReserveRequest
	4, // 3: balance.BalanceService.ReserveCancel:input_type -> balance.ReserveCancelRequest
	5, // 4: balance.BalanceService.ReserveConfirm:input_type -> balance.ReserveConfirmRequest
	6, // 5: balance.BalanceService.Transfer:input_type -> balance.TransferRequest
	7, // 6: balance.BalanceService.AuthSignIn:input_type -> balance.AuthSignInRequest
	1, // 7: balance.BalanceService.GetBalance:output_type -> balance.GetBalanceResponse
	9, // 8: balance.BalanceService.Deposit:output_type -> google.protobuf.Empty
	9, // 9: balance.BalanceService.Reserve:output_type -> google.protobuf.Empty
	9, // 10: balance.BalanceService.ReserveCancel:output_type -> google.protobuf.Empty
	9, // 11: balance.BalanceService.ReserveConfirm:output_type -> google.protobuf.Empty
	9, // 12: balance.BalanceService.Transfer:output_type -> google.protobuf.Empty
	8, // 13: balance.BalanceService.AuthSignIn:output_type -> balance.AuthSignInResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_balance_proto_init() }
func file_balance_proto_init() {
	if File_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_proto_goTypes,
		DependencyIndexes: file_balance_proto_depIdxs,
		MessageInfos:      file_balance_proto_msgTypes,
	}.Build()
	File_balance_proto = out.File
	file_balance_proto_goTypes = nil
	file_balance_proto_depIdxs = nil
}
