basePath: /api/v1
definitions:
  github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error:
    properties:
      error:
        type: string
    type: object
  ? github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_get_balance_responseBody
  : properties:
      result:
        $ref: '#/definitions/internal_balance_adapters_http_handlers_get_balance.responseBody'
    type: object
  ? github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_report_revenue_responseBody
  : properties:
      result:
        $ref: '#/definitions/internal_balance_adapters_http_handlers_report_revenue.responseBody'
    type: object
  ? github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_report_transactions_responseBody
  : properties:
      result:
        $ref: '#/definitions/internal_balance_adapters_http_handlers_report_transactions.responseBody'
    type: object
  ? github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_signin_responseBody
  : properties:
      result:
        $ref: '#/definitions/internal_balance_adapters_http_handlers_signin.responseBody'
    type: object
  github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.ResultEmpty:
    properties:
      result:
        type: object
    type: object
  internal_balance_adapters_http_handlers_deposit.requestBody:
    properties:
      amount:
        type: integer
      source:
        type: string
      user_id:
        type: integer
    type: object
  internal_balance_adapters_http_handlers_get_balance.responseBody:
    properties:
      available:
        type: integer
      reserved:
        type: integer
    type: object
  internal_balance_adapters_http_handlers_report_revenue.responseBody:
    properties:
      records:
        items:
          $ref: '#/definitions/internal_balance_adapters_http_handlers_report_revenue.responseRecord'
        type: array
    type: object
  internal_balance_adapters_http_handlers_report_revenue.responseRecord:
    properties:
      product_id:
        type: integer
      product_title:
        type: string
      total_revenue:
        type: integer
    type: object
  internal_balance_adapters_http_handlers_report_transactions.responseBody:
    properties:
      cursor:
        type: string
      has_more:
        type: boolean
      transactions:
        items: {}
        type: array
    type: object
  internal_balance_adapters_http_handlers_reserve.requestBody:
    properties:
      amount:
        type: integer
      order_id:
        type: integer
      product_id:
        type: integer
      product_title:
        type: string
      user_id:
        type: integer
    type: object
  internal_balance_adapters_http_handlers_reserve_cancel.requestBody:
    properties:
      amount:
        type: integer
      order_id:
        type: integer
      product_id:
        type: integer
      user_id:
        type: integer
    type: object
  internal_balance_adapters_http_handlers_reserve_confirm.requestBody:
    properties:
      amount:
        type: integer
      order_id:
        type: integer
      product_id:
        type: integer
      user_id:
        type: integer
    type: object
  internal_balance_adapters_http_handlers_signin.requestBody:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  internal_balance_adapters_http_handlers_signin.responseBody:
    properties:
      token:
        type: string
    type: object
  internal_balance_adapters_http_handlers_transfer.requestBody:
    properties:
      amount:
        type: integer
      from:
        type: integer
      to:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: nikita@kanash.in
    name: API Support
    url: https://github.com/nktknshn
  description: Balance Microservice API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Balance Microservice API
  version: "1.0"
paths:
  /api/v1/balance/{user_id}:
    get:
      consumes:
      - application/json
      description: Get balance
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_get_balance_responseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Get balance
      tags:
      - balance
  /api/v1/balance/deposit:
    post:
      consumes:
      - application/json
      description: Deposit money to account
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_balance_adapters_http_handlers_deposit.requestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.ResultEmpty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Deposit money
      tags:
      - deposit
  /api/v1/balance/reserve:
    post:
      consumes:
      - application/json
      description: Reserve money
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_balance_adapters_http_handlers_reserve.requestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.ResultEmpty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Reserve
      tags:
      - reserve
  /api/v1/balance/reserve/cancel:
    post:
      consumes:
      - application/json
      description: Cancel money reservation
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_balance_adapters_http_handlers_reserve_cancel.requestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.ResultEmpty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Reserve cancel
      tags:
      - reserve_cancel
  /api/v1/balance/reserve/confirm:
    post:
      consumes:
      - application/json
      description: Confirm money reservation
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_balance_adapters_http_handlers_reserve_confirm.requestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.ResultEmpty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Reserve confirm
      tags:
      - reserve_confirm
  /api/v1/balance/transfer:
    post:
      consumes:
      - application/json
      description: Transfer money
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_balance_adapters_http_handlers_transfer.requestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.ResultEmpty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Transfer
      tags:
      - transfer
  /api/v1/report/revenue:
    get:
      consumes:
      - application/json
      description: Report revenue
      parameters:
      - description: Year
        in: query
        name: year
        required: true
        type: integer
      - description: Month
        in: query
        name: month
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_report_revenue_responseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Report revenue
      tags:
      - report_revenue
  /api/v1/report/transactions/{user_id}:
    get:
      consumes:
      - application/json
      description: Report transactions
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Cursor
        in: query
        name: cursor
        type: string
      - description: Sorting
        in: query
        name: sorting
        type: string
      - description: Sorting Direction
        in: query
        name: sorting_direction
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_report_transactions_responseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      security:
      - BearerAuth: []
      summary: Report transactions
      tags:
      - report_transactions
  /api/v1/signin:
    post:
      consumes:
      - application/json
      description: Sign in
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_balance_adapters_http_handlers_signin.requestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Result-internal_balance_adapters_http_handlers_signin_responseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_nktknshn_avito-internship-2022_internal_balance_adapters_http_handlers_handlers_builder.Error'
      summary: Sign in
      tags:
      - signin
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
