auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_listen_port: 9096
  grpc_server_max_concurrent_streams: 1000

limits_config:
  metric_aggregation_enabled: true
  allow_structured_metadata: true
  volume_enabled: true

compactor:
  compaction_interval: 2h

common:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
  filesystem:
    directory: /tmp/loki/chunks

pattern_ingester:
  enabled: true
