@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDY2OTY3MDksImlhdCI6MTc0NjYxMDMwOSwiRGF0YSI6eyJBdXRoVXNlcklEIjoxLCJBdXRoVXNlclJvbGUiOiJhZG1pbiJ9fQ.xroPPuiQ-cMsKgmuiINTtHngHULs9MDw-U_MvvpfMQ4

###

GET http://127.0.0.1:5050/api/v1/balance/1
Authorization: Bearer {{token}} 

###

GET http://127.0.0.1:5050/api/v1/balance/0

###

POST http://localhost:5050/api/v1/balance/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 1,
    "amount": 100,
    "source": "credit"
}

###

POST http://localhost:5050/api/v1/balance/reserve
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 1,
    "product_id": 2,
    "product_title": "test product",
    "order_id": 5,
    "amount": 100
}

###

POST http://localhost:5050/api/v1/balance/reserve/confirm
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 1,
    "product_id": 1,
    "order_id": 5,
    "amount": 100
}

###

POST http://localhost:5050/api/v1/signin
Content-Type: application/json

{
    "password": "admin1234",
    "username": "admin"
}

###

# invalid cursor
GET http://localhost:5050/api/v1/report/transactions/1?limit=10&cursor=1&sorting=updated_at&sorting_direction=desc
Authorization: Bearer {{token}}

###

# valid request
GET http://localhost:5050/api/v1/report/transactions/1?limit=10&sorting=updated_at&sorting_direction=asc
Authorization: Bearer {{token}}


###

OPTIONS http://localhost:5050/api/v1/balance/deposit

###

GET http://localhost:5050/api/v1/report/revenue?year=2025&month=5
Authorization: Bearer {{token}}

###

GET http://localhost:5050/api/v1/report/revenue/export?year=2025&month=5
Authorization: Bearer {{token}}

###

GET http://localhost:5050/api/v1/report/revenue
Authorization: Bearer {{token}}


### 

GET http://localhost:5050/data/report_revenue_export/35554a59-c801-4db2-96ee-f1f82b30003b_revenue_report_2025-05-05_14-12-12.csv


###
GET http://localhost:5050/data/report_revenue_export/96212492-5cc6-4991-b8e0-a9452f2f264c_revenue_report_2025-05-06_19-07-50.csv.zip
