@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDYyODk5MDAsImlhdCI6MTc0NjI4NjMwMCwiRGF0YSI6eyJBdXRoVXNlcklEIjoxLCJBdXRoVXNlclJvbGUiOiJhZG1pbiJ9fQ.UiGAPhNYGewyKDZsr-CaRoO3t6fyrrDHOxX0EWFCysI

###

GET http://127.0.0.1:5050/api/v1/balance/1
Authorization: Bearer {{token}} 

###

GET http://127.0.0.1:5050/api/v1/balance/0

###

POST http://localhost:5050/api/v1/balance/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 1,
    "amount": 100,
    "source": "credit"
}

###

POST http://localhost:5050/api/v1/balance/reserve
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 1,
    "product_id": 2,
    "product_title": "test product",
    "order_id": 5,
    "amount": 100
}

###

POST http://localhost:5050/api/v1/balance/reserve/confirm
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 1,
    "product_id": 1,
    "order_id": 5,
    "amount": 100
}

###

POST http://localhost:5050/api/v1/signin
Content-Type: application/json

{
    "password": "admin1234",
    "username": "admin"
}

###

# invalid cursor
GET http://localhost:5050/api/v1/report/transactions/1?limit=10&cursor=1&sorting=updated_at&sorting_direction=desc
Authorization: Bearer {{token}}

###

# valid request
GET http://localhost:5050/api/v1/report/transactions/1?limit=10&sorting=updated_at&sorting_direction=asc
Authorization: Bearer {{token}}


###

OPTIONS http://localhost:5050/api/v1/balance/deposit

###

GET http://localhost:5050/api/v1/report/revenue?year=2025&month=5
Authorization: Bearer {{token}}

###

GET http://localhost:5050/api/v1/report/revenue
Authorization: Bearer {{token}}
